### ISSUE TITLE
ClientConnection Exceptions

### ISSUE THREAD

**Issue by Lucisano** [ukfast/sdk-dotnet#5]
Came across an issue that would produce a UKFastClientRequest Exception when the request is fine as is the result.

It's actually throwing this when the model are incorrect. In this case it was a string trying to be cast into an int during deserialisation. 

Could do with a catch on JsonDeserialisation exceptions to throw a different type and give better information to the developer

**Comment by kataras12** [comment]
something liek this might do it? https://github.com/ukfast/sdk-dotnet/pull/8
